# Generated by Django 4.2.4 on 2023-08-26 19:36

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=calc.models.user_derectory_path),
        ),
    ]
